routes/web.php
<?php

use App\Http\Controllers\WelcomeController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\TagsController;
use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\PostsController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [WelcomeController::class, 'index'])->name('welcome');
Route::get('/blog/{post}', [WelcomeController::class, 'show'])->name('blog.show');
Route::get('/blog/categort/{category}', [WelcomeController::class, 'category'])->name('blog.category');
Route::get('/blog/tag/{tag}', [WelcomeController::class, 'tag'])->name('blog.tag');

Auth::routes();
Route::middleware(['auth'])->group(function (){
    Route::get('/home', [HomeController::class, 'index'])->name('home');

//This will create routes for 7 default actions automatically.
    Route::resource('categories', CategoriesController::class);
    Route::resource('tags', TagsController::class);
    Route::resource('posts', PostsController::class);
    Route::delete('/trash/{post}', [PostsController::class, 'trash'])->name('posts.trash');
    Route::get('/trashed', [PostsController::class, 'trashed'])->name('posts.trashed');
    Route::put('/restore/{post}', [PostsController::class, 'restore'])->name('posts.restore');
});
Route::middleware(['auth', 'admin'])->group(function() {
    Route::get('/users', [UsersController::class, 'index'])->name('users.index');
    Route::put('/users/{user}/make-admin', [UsersController::class, 'makeAdmin'])->name('users.make-admin');
});

app/Models/Tag.php
<?php

namespace App\Models;

use App\DTO\TagDto;
use App\Helpers\BaseModel;
use App\Helpers\Utils;
use App\Interfaces\TagConstants;
use Illuminate\Database\Eloquent\ModelNotFoundException;

class Tag extends BaseModel implements TagConstants
{
    protected $fillable = ['name'];

    public static function persistTag(TagDto $tagDto): Tag
    {
        //Validation
        Utils::validateOrThrow(self::CREATE_RULES, ['name'=>$tagDto->name]);

        return Tag::create($tagDto->except('id')->toArray());
    }

    public function updateTag(TagDto $tagDto) : self
    {
        $this->update($tagDto->except('id')->toArray());
        return $this;
    }

    public function posts()
    {
        return $this->belongsToMany(Post::class)->withTimestamps();
    }

    public static function getCreateValidationRules(): array
    {
        return self::CREATE_RULES;
    }

    public static function getUpdateValidationRules(): array
    {
        return self::UPDATE_RULES;
    }
}

app/Http/Controllers/TagsController.php
<?php

namespace App\Http\Controllers;

use App\DTO\TagDto;
use App\Http\Requests\Tag\CreateTagRequest;
use App\Http\Requests\Tag\UpdateTagRequest;
use App\Models\Tag;
use App\Services\TagService;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Http\Request;

class TagsController extends Controller
{
    private TagService $tagService;
    /**
     * CategoriesController constructor.
     */
    public function __construct(TagService $ref)
    {
        $this->tagService = $ref;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = $this->tagService->index();
        return view('tags.index', $data);
    }
    public function create()
    {
        return view('tags.create');
    }
    public function store(CreateTagRequest $request)
    {
        try {
            $this->tagService->create(new TagDto(
                id: 0,
                name: $request->name
            ));
        } catch (\Throwable $e){
            session()->flash('error', 'Failed to add Tag!');
            return redirect(route('tags.index'));
        }
        session()->flash('success', 'Tag Added Successfully');
        return redirect(route('tags.index'));
    }
    public function edit(Tag $tag)
    {
        $data = $this->tagService->editData($tag);
        return view('tags.edit', $data);
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateTagRequest $request, Tag $tag)
    {
        try {
            if($this->tagService->update($tag, new TagDto(id: $tag->id, name: $request->name)) === false)
            {
                session()->flash('success', 'No changes made!');
            } else {
                session()->flash('success', 'Tag Updated Successful!');
            }
        } catch (\Throwable $e){
            session()->flash('error', 'Failed to update Tag!');
            return redirect(route('tags.index'));
        }

        return redirect(route('tags.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tag $tag)
    {
        if(!($this->tagService->delete($tag))) {
            session()->flash('error', 'Tag cannot be deleted as it is associated with some post!');
            return redirect()->back();
        }
        session()->flash('success', 'Tag Deleted Successfully!');
        return redirect(route('tags.index'));
    }
}

resources/views/tags/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="card">
        <div class="card-header">Add Tag</div>

        <div class="card-body">
            <form action="{{ route('tags.store') }}" method="POST">
                @csrf
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text"
                            value="{{ old('name') }}"
                            class="form-control @error('name') is-invalid @enderror"
                            name="name" id="name">
                    @error('name')
                        <p class="text-danger">{{ $message }}</p>
                    @enderror
                </div>
                <div class="form-group">
                    <button class="btn btn-success" type="submit">Add Tag</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/tags/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="card">
        <div class="card-header">Add Category</div>

        <div class="card-body">
            <form action="{{ route('tags.update', $tagDto->id) }}" method="POST">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text"
                           value="{{ old('name', $tagDto->name) }}"
                           class="form-control @error('name') is-invalid @enderror"
                           name="name" id="name">
                    @error('name')
                        <p class="text-danger">{{ $message }}</p>
                    @enderror
                </div>
                <div class="form-group">
                    <button class="btn btn-success" type="submit">Update</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/tags/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="d-flex justify-content-end mb-3">
        <a href="{{ route('tags.create') }}" class="btn btn-primary">Add Tag</a>
    </div>
    <div class="card">
        <div class="card-header">Tags</div>

        <div class="card-body">
            <table class="table table-bordered">
                <thead>
                    <th>Name</th>
                    <th>Posts</th>
                    <th>Actions</th>
                </thead>
                <tbody>
                    @foreach($tagCollection as $tagDto)
                        <tr>
                            <td>
                                {{ $tagDto->name }}
                            </td>
                            <td>
                                {{ $tagDto->postCount }}
                            </td>
                            <td>
                                <a href="{{ route('tags.edit', $tagDto->id) }}" class="btn btn-primary btn-sm">Edit</a>
                                <a href="#" class="btn btn-danger btn-sm"
                                   onclick="displayModalForm({{$tagDto->id}})"
                                    data-toggle="modal"
                                    data-target="#deleteModal">Delete</a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>

    <!-- DELETE MODAL -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Delete Modal</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="" METHOD="POST" id="deleteForm">
                    @csrf
                    @method('DELETE')
                    <div class="modal-body">
                        <p>Are you sure you want to delete Tag??</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-danger">Delete Tag</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection

@section('page-level-scripts')
    <script type="text/javascript">
        function displayModalForm($tagId) {
            var url = '/tags/' + $tagId;
            $("#deleteForm").attr('action', url);
        }
    </script>
@endsection