routes/web.php
<?php

use App\Http\Controllers\WelcomeController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\TagsController;
use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\PostsController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [WelcomeController::class, 'index'])->name('welcome');
Route::get('/blog/{post}', [WelcomeController::class, 'show'])->name('blog.show');
Route::get('/blog/categort/{category}', [WelcomeController::class, 'category'])->name('blog.category');
Route::get('/blog/tag/{tag}', [WelcomeController::class, 'tag'])->name('blog.tag');

Auth::routes();
Route::middleware(['auth'])->group(function (){
    Route::get('/home', [HomeController::class, 'index'])->name('home');

//This will create routes for 7 default actions automatically.
    Route::resource('categories', CategoriesController::class);
    Route::resource('tags', TagsController::class);
    Route::resource('posts', PostsController::class);
    Route::delete('/trash/{post}', [PostsController::class, 'trash'])->name('posts.trash');
    Route::get('/trashed', [PostsController::class, 'trashed'])->name('posts.trashed');
    Route::put('/restore/{post}', [PostsController::class, 'restore'])->name('posts.restore');
});
Route::middleware(['auth', 'admin'])->group(function() {
    Route::get('/users', [UsersController::class, 'index'])->name('users.index');
    Route::put('/users/{user}/make-admin', [UsersController::class, 'makeAdmin'])->name('users.make-admin');
});

app/Models/Post.php
<?php

namespace App\Models;

use App\DTO\PostDto;
use App\Helpers\BaseModel;
use App\Helpers\Utils;
use App\Interfaces\PostConstants;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Validation\ValidationException;

class Post extends BaseModel implements PostConstants
{
    use SoftDeletes;

    protected $dates = ['published_at'];
    protected $fillable = [
        'title',
        'category_id',
        'excerpt',
        'content',
        'image',
        'published_at',
        'user_id'
    ];

    /**
     * @param int $userId
     * @param int $categoryId
     * @param PostDto $postDto
     * @param array $tags
     * @return Post
     * @throws \Throwable
     *
     */
    public static function persistPost(PostDto $postDto): Post
    {
        //Validation
        Utils::validateOrThrow(array_diff_key(self::CREATE_RULES, ['image'=>'']), $postDto->toArray());

        //Creation
        $post = null;
        DB::transaction(function () use ($postDto, &$post) {
            if ($postDto->imageFile === null)
            {
                throw ValidationException::withMessages([
                    'image' => ['image field is required']
                ]);
            }
            $postDto->image = $postDto->imageFile->store('posts');

            $post = Post::create($postDto->except('id', 'tags')->toArray());
            $post->tags()->attach($postDto->collection_of_tags->pluck('id')->toArray());
        });
        return $post;
    }

    public function updatePost(PostDto $postDto): self
    {
        //Validation


        //Creation
        DB::transaction(function () use ($postDto) {
            $data = $postDto->except('id', 'tags')->toArray();
            if($postDto->imageFile !== null){
                $data['image'] = $postDto->imageFile->store('posts');
            } else {
                unset($data['image']);
            }
            $this->update($data);
            $this->tags()->sync($postDto->collection_of_tags->pluck('id')->toArray());
        });
        return $this;
    }

    /*
     * HELPER FUNCTIONS
     */
    public function deleteImage()
    {
        Storage::delete($this->image);
    }
    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class)->withTimestamps();

    }
    public function hasTag($tag_id)
    {
        return in_array($tag_id, $this->tags->pluck('id')->toArray());
    }

    public function author()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    /**
     * QUERY SCOPES
     */

     public function scopePublished($query) {
         return $query->where('published_at', '<=', now());
     }

     public function scopeSearch($query) {
         $search = request('search');
         if($search) {
             return $query->where('title', 'like', "%$search%");
         }
         return $query;
     }

    public static function getCreateValidationRules(): array
    {
        return self::CREATE_RULES;
    }

    public static function getUpdateValidationRules(): array
    {
        return self::UPDATE_RULES;
    }
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use App\DTO\BaseDTO;
use App\DTO\Casters\TagCollectionCaster;
use App\DTO\Collection\TagCollection;
use App\DTO\PostDto;
use App\DTO\TagDto;
use App\Models\Category;
use App\Http\Requests\Categories\UpdateCategoryRequest;
use App\Http\Requests\Post\CreatePostRequest;
use App\Http\Requests\Post\UpdatePostRequest;
use App\Models\Post;
use App\Models\Tag;
use App\Services\PostService;

class PostsController extends Controller
{
    private PostService $postService;
    public function __construct(PostService $ref)
    {
        $this->postService = $ref;
        $this->middleware(['verifyCategoriesCount'])->only('create', 'store');
        $this->middleware(['validateAuthor'])->only('edit', 'update', 'destroy', 'trash');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = $this->postService->index(auth()->user()->isAdmin());
        return view('posts.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = $this->postService->getPostBindings();
        return view('posts.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreatePostRequest $request)
    {
        //Image Upload and stores the name of image
        // run command: php artisan storage:link
        $image = $request->file('image');

        $postDto = new PostDto(
            id: 0,
            category_id: $request->category_id,
            user_id: auth()->id(),
            collection_of_tags: $this->getTagCollection($request->tags),
            title: $request->title,
            excerpt: $request->excerpt,
            content: $request->content,
            imageFile: $image,
            published_at: $request->published_at,
        );

        try {
            $this->postService->create($postDto);
        } catch (\Throwable $e){
            session()->flash('error', 'Failed to add Post!');
            return redirect(route('posts.index'));
        }
        session()->flash('success', 'Post Created Successfully!');
        return redirect(route('posts.index'));
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        $data = $this->postService->editData($post);
        return view('posts.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(UpdatePostRequest $request, Post $post)
    {
        $image = $request->file('image');

        $postDto = new PostDto(
            id: 0,
            category_id: $request->category_id,
            user_id: auth()->id(),
            collection_of_tags: $this->getTagCollection($request->tags),
            title: $request->title,
            excerpt: $request->excerpt,
            content: $request->content,
            imageFile: $image,
            published_at: $request->published_at,
        );

        try{
            $this->postService->update($post, $postDto);
        } catch (\Throwable $e){
            session()->flash('error', 'Failed to update Post!');
            return redirect(route('posts.index'));
        }
        session()->flash('success', 'Post Updated Successfully!');
        return redirect(route('posts.index'));
    }

    private function getTagCollection($tags)
    {
        $tagCollection = new TagCollection();
        foreach ($tags as $tagId){
            $tagCollection->push(TagDto::fromModel(Tag::find($tagId)));
        }
        return $tagCollection;
    }

    /**
     * Remove the specified resource from storage permanently.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->postService->destroy($id);
        session()->flash('success', 'Post Deleted Successfully!');
        return redirect()->back();
    }

    /*
     * Soft deletes the Post
     */
    public function trash(Post $post)
    {
        $this->postService->trash($post);
        session()->flash('success', 'Post trashed successfully!');
        return redirect(route('posts.index'));
    }
    public function trashed()
    {
        $trashed = $this->postService->trashed();
        return view('posts.trashed')->with('posts', $trashed);
    }

    public function restore($id)
    {
        $this->postService->restore($id);
        session()->flash('success', 'Post restored successfully!');
        return redirect(route('posts.index'));
    }
}

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('live-preview-btn')
    <div class="text-center mt-4">
        <button class="btn btn-danger" id="preview-btn" data-toggle="modal" data-target="#previewModal" style="width: 100%">Live Preview</button>
    </div>
@endsection

@section('content')
    <div class="card">
        <div class="card-header">Add Post</div>
        <div class="card-body">
            <form action="{{ route('posts.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text"
                           value="{{ old('title') }}"
                           class="form-control @error('title') is-invalid @enderror"
                           id="title"
                           name="title" id="title">
                    @error('title')
                        <p class="text-danger">{{ $message }}</p>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="category_id">Category</label>
                    <select name="category_id" id="category_id" class="form-control select2">
                        <option value="" selected disabled>SELECT</option>
                        @foreach($categoyCollection as $categoryDto)
                            <option value="{{ $categoryDto->id }}">{{ $categoryDto->name }}</option>
                        @endforeach
                    </select>
                </div>

                <div class="form-group">
                    <label for="tags">Tags</label>
                    <select name="tags[]" id="tags" class="form-control select2" multiple>
                        @foreach($tagCollection as $tagDto)
                            <option value="{{ $tagDto->id }}">{{ $tagDto->name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="excerpt">Excerpt</label>
                    <textarea name="excerpt"
                              id="excerpt"
                              class="form-control @error('excerpt') is-invalid @enderror"
                              rows="4">{{ old('excerpt') }}</textarea>
                    @error('excerpt')
                        <p class="text-danger">{{ $message }}</p>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="content">Content</label>
                    <input type="hidden" id="content" name="content">
                    <trix-editor input="content"></trix-editor>

                    @error('content')
                        <p class="text-danger">{{ $message }}</p>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="published_at">Published At</label>
                    <input type="text"
                           value="{{ old('published_at') }}"
                           class="form-control"
                           name="published_at" id="published_at">
                    @error('published_at')
                        <p class="text-danger">{{ $message }}</p>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="image">Image</label>
                    <input type="file"
                            onchange="readURL(this);"
                           class="form-control @error('image') is-invalid @enderror"
                           name="image" id="image">
                    @error('image')
                        <p class="text-danger">{{ $message }}</p>
                    @enderror
                </div>
                <div class="form-group">
                    <button class="btn btn-success" type="submit">Add Post</button>
                </div>
            </form>
        </div>
    </div>

    <div class="modal fade" id="previewModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-xl">
            <div class="modal-content" style="height: 70vh">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Blog Preview</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" style="max-width: 100%; height:40vh;">
                    <div class="blog-three-mini">
                        <div class="clearfix">
                            <div><h2 class="color-dark pull-left" id="preview-title">Title...</h2></div>
                        </div>
                        <div class="blog-three-attrib">
                            <div><i class="fa fa-calendar"></i>Live Preview</div> |
                            <div><i class="fa fa-pencil"></i><a href="#" id="preview-author">{{ Auth::user()->name }}</a></div> |
                            <div>
                                Share:  <a href="#"><i class="fa fa-facebook-official"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-linkedin"></i></a>
                                <a href="#"><i class="fa fa-google-plus"></i></a>
                                <a href="#"><i class="fa fa-pinterest"></i></a>
                            </div>
                        </div>

                        <img src="https://via.placeholder.com/1920x1080" alt="Blog Image" id="img-preview" class="img-responsive" width="100%">
                        <div class="lead mt25" id="preview-content">
                            Some Content, Some Content, Some Content, Some Content, Some Content, Some Content, Some Content, Some Content, Some Content, Some Content, Some Content, Some Content, Some Content, Some Content, Some Content, Some Content, Some Content, Some Content, Some Content, Some Content, Some Content, Some Content, Some Content, Some Content,
                        </div>

                        <div class="blog-post-read-tag mt50">
                            <i class="fa fa-tags"></i> Tags:
                                <div id="preview-tag-parent" style="display: inline-block">

                                </div>
                        </div>

                        <div class="blog-post-author mb50 pt30 bt-solid-1">
                            <img src="{{ \Thomaswelton\LaravelGravatar\Facades\Gravatar::src(Auth::user()->email) }}" class="img-circle" alt="image">
                            <span class="blog-post-author-name">{{ Auth::user()->name }}</span> <a href="https://twitter.com/booisme"><i class="fa fa-twitter"></i></a>
                            <p>
                                {{ Auth::user()->about == ""? "N.A" : Auth::user()->about }}
                            </p>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('page-level-scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
    <script src="{{ asset('assets/js/preview/app.js') }}"></script>
    <script>
        flatpickr("#published_at", {
            enableTime: true
        });
        $(document).ready(function() {
            $('.select2').select2({
                placeholder: "select..."
            });
        });
    </script>
    @include('layouts.blog/_js')

@endsection
@section('page-level-styles')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css">
    @include('layouts.blog/_css')
@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="card">
        <div class="card-header">Edit Post</div>

        <div class="card-body">
            <form action="{{ route('posts.update', $postDto->id) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text"
                           value="{{ old('title', $postDto->title) }}"
                           class="form-control @error('title') is-invalid @enderror"
                           name="title" id="title">
                    @error('title')
                        <p class="text-danger">{{ $message }}</p>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="category_id">Category</label>
                    <select name="category_id" id="category_id" class="form-control select2">
                        <option value="" selected disabled>SELECT</option>
                        @foreach($categoyCollection as $categoryDto)
                            <option value="{{ $categoryDto->id }}" @if($postDto->category_id == $categoryDto->id) selected @endif>{{ $categoryDto->name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="tags">Tags</label>
                    <select name="tags[]" id="tags" class="form-control select2" multiple>
                        @foreach($tagCollection as $tagDto)
                            <option value="{{ $tagDto->id }}"
                                {{ old('tags') ? (in_array($tagDto->id, old('tags')) ?'selected' : '') : (in_array($tagDto->id, $postDto->collection_of_tags->pluck('id')->toArray()) ? 'selected' : '') }}>{{ $tagDto->name }}
                            </option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="excerpt">Excerpt</label>
                    <textarea name="excerpt"
                              id="excerpt"
                              class="form-control @error('excerpt') is-invalid @enderror"
                              rows="4">{{ old('excerpt', $postDto->excerpt) }}</textarea>
                    @error('excerpt')
                        <p class="text-danger">{{ $message }}</p>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="content">Content</label>
                    <input type="hidden" id="content" name="content" value="{{ old('content', $postDto->content) }}">
                    <trix-editor input="content"></trix-editor>

                    @error('content')@section('page-level-scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
    <script>
        flatpickr("#published_at", {
            enableTime: true
        });
        $(document).ready(function() {
            $('.select2').select2();
        });
    </script>
@endsection
@section('page-level-styles')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css">
@endsection

                        <p class="text-danger">{{ $message }}</p>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="published_at">Published At</label>
                    <input type="text"
                           value="{{ old('published_at', $postDto->published_at) }}"
                           class="form-control"
                           name="published_at" id="published_at">
                    @error('published_at')
                        <p class="text-danger">{{ $message }}</p>
                    @enderror
                </div>
                <div class="form-group">
                    <img src="{{ asset('storage/'.$postDto->image) }}" alt="">
                </div>
                <div class="form-group">
                    <label for="image">Image</label>
                    <input type="file"
                           class="form-control @error('image') is-invalid @enderror"
                           name="image" id="image">
                    @error('image')
                        <p class="text-danger">{{ $message }}</p>
                    @enderror
                </div>
                <div class="form-group">
                    <button class="btn btn-success" type="submit">Update Post</button>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('page-level-scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
    <script>
        flatpickr("#published_at", {
            enableTime: true
        });
        $(document).ready(function() {
            $('.select2').select2();
        });
    </script>
@endsection
@section('page-level-styles')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css">
@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="d-flex justify-content-end mb-3">
        <a href="{{ route('posts.create') }}" class="btn btn-primary">Add Post</a>
    </div>
    <div class="card">
        <div class="card-header">Posts</div>

        <div class="card-body">
            @if($posts->count() > 0)
                <table class="table table-bordered">
                <thead>
                    <th>Image</th>
                    <th>Title</th>
                    <th>Excerpt</th>
                    <th>Author</th>
                    <th>Category</th>
                    <th>Actions</th>
                </thead>
                <tbody>
                    @foreach($posts as $post)
                        <tr>
                            <td>
                                <img src="{{asset('storage/'.$post->image)}}" alt="Post Image" width="128">
                            </td>
                            <td>{{ $post->title }}</td>
                            <td>{{ $post->excerpt }}</td>
                            <td>{{ $post->author->name }}</td>
                            <td>{{ $post->category->name }}</td>
                            <td>
                                <a href="{{ route('posts.edit', $post->id) }}" class="btn btn-primary btn-sm">Edit</a>
                                <a href="#" class="btn btn-danger btn-sm"
                                   onclick="displayModalForm({{$post}})"
                                   data-toggle="modal"
                                   data-target="#deleteModal">Trash</a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            @else
                <h5>No posts!</h5>
            @endif
        </div>

        <div class="card-footer">
            {{ $posts->links() }}
        </div>
    </div>

    <!-- DELETE MODAL -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Delete Modal</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="" METHOD="POST" id="deleteForm">
                    @csrf
                    @method('DELETE')
                    <div class="modal-body">
                        <p>Are you sure you want to delete Post??</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-danger">Delete Post</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection

@section('page-level-scripts')
    <script type="text/javascript">
        function displayModalForm($post) {
            var url = '/trash/' + $post.id;
            $("#deleteForm").attr('action', url);
        }
    </script>
@endsection

resources/views/posts/trashed.blade.php
@extends('layouts.app')

@section('content')

    <div class="d-flex justify-content-end mb-3">
        <a href="{{ route('posts.create') }}" class="btn btn-primary">Add Post</a>
    </div>
    <div class="card">
        <div class="card-header">Trashed Posts</div>

        <div class="card-body">
            @if($posts->count() > 0)
                <table class="table table-bordered">
                <thead>
                <th>Image</th>
                <th>Title</th>
                <th>Excerpt</th>
                <th>Actions</th>
                </thead>
                <tbody>
                    @foreach($posts as $post)
                        <tr>
                            <td>
                                <img src="{{asset('storage/'.$post->image)}}" alt="Post Image" width="128">
                            </td>
                            <td>{{ $post->title }}</td>
                            <td>{{ $post->excerpt }}</td>
                            <td>
                                <form action="{{ route('posts.restore', $post->id) }}" method="POST">
                                    @csrf
                                    @method('PUT')
                                    <button class="btn btn-primary btn-sm">Restore</button>
                                </form>
                                <a href="#" class="btn btn-danger btn-sm"
                                   onclick="displayModalForm({{$post}})"
                                   data-toggle="modal"
                                   data-target="#deleteModal">Delete</a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            @else
                <h5>No trashed posts!</h5>
            @endif
        </div>
        <div class="card-footer">
            {{ $posts->links() }}
        </div>
    </div>

    <!-- DELETE MODAL -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Delete Modal</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="" METHOD="POST" id="deleteForm">
                    @csrf
                    @method('DELETE')
                    <div class="modal-body">
                        <p>Are you sure you want to delete post??</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-danger">Delete Post</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection

@section('page-level-scripts')
    <script type="text/javascript">
        function displayModalForm($post) {
            var url = '/posts/' + $post.id;
            $("#deleteForm").attr('action', url);
        }
    </script>
@endsection