routes/web.php
<?php

use App\Http\Controllers\WelcomeController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\TagsController;
use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\PostsController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [WelcomeController::class, 'index'])->name('welcome');
Route::get('/blog/{post}', [WelcomeController::class, 'show'])->name('blog.show');
Route::get('/blog/categort/{category}', [WelcomeController::class, 'category'])->name('blog.category');
Route::get('/blog/tag/{tag}', [WelcomeController::class, 'tag'])->name('blog.tag');

Auth::routes();
Route::middleware(['auth'])->group(function (){
    Route::get('/home', [HomeController::class, 'index'])->name('home');

//This will create routes for 7 default actions automatically.
    Route::resource('categories', CategoriesController::class);
    Route::resource('tags', TagsController::class);
    Route::resource('posts', PostsController::class);
    Route::delete('/trash/{post}', [PostsController::class, 'trash'])->name('posts.trash');
    Route::get('/trashed', [PostsController::class, 'trashed'])->name('posts.trashed');
    Route::put('/restore/{post}', [PostsController::class, 'restore'])->name('posts.restore');
});
Route::middleware(['auth', 'admin'])->group(function() {
    Route::get('/users', [UsersController::class, 'index'])->name('users.index');
    Route::put('/users/{user}/make-admin', [UsersController::class, 'makeAdmin'])->name('users.make-admin');
});

app/Models/Category.php
<?php

namespace App\Models;

use App\DTO\CategoryDto;
use App\Helpers\BaseModel;
use App\Helpers\Utils;
use App\Interfaces\CategoryConstants;

class Category extends BaseModel implements CategoryConstants
{
    protected $fillable = ['name'];
    public static function persistCategory(CategoryDto $categoryDto): Category
    {
        //Validation
        Utils::validateOrThrow(self::CREATE_RULES, ['name'=>$categoryDto->name]);

        return Category::create($categoryDto->except('id')->toArray());
    }

    public function updateCategory(CategoryDto $categoryDto): self
    {
        $this->update($categoryDto->except('id')->toArray());
        return $this;
    }

    public function posts()
    {
        return $this->hasMany(Post::class);
    }

    public static function getCreateValidationRules(): array
    {
        return self::CREATE_RULES;
    }

    public static function getUpdateValidationRules(): array
    {
        return self::UPDATE_RULES;
    }
}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use App\DTO\CategoryDto;
use App\Models\Category;
use App\Http\Requests\Categories\CreateCategoryRequest;
use App\Http\Requests\Categories\UpdateCategoryRequest;
use App\Services\CategoryService;
use Illuminate\Http\Request;

class CategoriesController extends Controller
{
    private CategoryService $categoryService;
    /**
     * CategoriesController constructor.
     */
    public function __construct(CategoryService $ref)
    {
        $this->categoryService = $ref;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = $this->categoryService->index();
        return view('categories.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateCategoryRequest $request)
    {
        try {
            $this->categoryService->create(new CategoryDto(
                id: 0,
                name: $request->name
            ));
        } catch (\Throwable $e){
            session()->flash('error', 'Failed to add Category!');
            return redirect(route('categories.index'));
        }
        session()->flash('success', 'Category Added Successfully');
        return redirect(route('categories.index'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        $data = $this->categoryService->editData($category);
        return view('categories.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCategoryRequest $request, Category $category)
    {
        try {
            if($this->categoryService->update($category, new CategoryDto(id: $category->id, name: $request->name)) === false)
            {
                session()->flash('success', 'No changes made!');
            } else {
                session()->flash('success', 'Category Updated Successful!');
            }
        } catch (\Throwable $e){
            session()->flash('error', 'Failed to update Category!');
            return redirect(route('categories.index'));
        }
        return redirect(route('categories.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        if(!($this->categoryService->delete($category))) {
            session()->flash('error', 'Category cannot be deleted as it is associated with some post!');
            return redirect()->back();
        }
        session()->flash('success', 'Category Deleted Successfully!');
        return redirect(route('categories.index'));
    }
}

resources/views/categories/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="card">
        <div class="card-header">Add Category</div>

        <div class="card-body">
            <form action="{{ route('categories.store') }}" method="POST">
                @csrf
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text"
                            value="{{ old('name') }}"
                            class="form-control @error('name') is-invalid @enderror"
                            name="name" id="name">
                    @error('name')
                        <p class="text-danger">{{ $message }}</p>
                    @enderror
                </div>
                <div class="form-group">
                    <button class="btn btn-success" type="submit">Add Category</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/categories/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="card">
        <div class="card-header">Add Category</div>

        <div class="card-body">
            <form action="{{ route('categories.update', $categoryDto->id) }}" method="POST">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text"
                           value="{{ old('name', $categoryDto->name) }}"
                           class="form-control @error('name') is-invalid @enderror"
                           name="name" id="name">
                    @error('name')
                    <p class="text-danger">{{ $message }}</p>
                    @enderror
                </div>
                <div class="form-group">
                    <button class="btn btn-success" type="submit">Update</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/categories/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="d-flex justify-content-end mb-3">
        <a href="{{ route('categories.create') }}" class="btn btn-primary">Add Category</a>
    </div>
    <div class="card">
        <div class="card-header">Categories</div>

        <div class="card-body">
            <table class="table table-bordered">
                <thead>
                    <th>Name</th>
                    <th>Actions</th>
                </thead>
                <tbody>
                    @foreach($categoyCollection as $categoryDto)
                        <tr>
                            <td>
                                {{ $categoryDto->name }}
                            </td>
                            <td>
                                <a href="{{ route('categories.edit', $categoryDto->id) }}" class="btn btn-primary btn-sm">Edit</a>
                                <a href="#" class="btn btn-danger btn-sm"
                                   onclick="displayModalForm({{$categoryDto->id}})"
                                    data-toggle="modal"
                                    data-target="#deleteModal">Delete</a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>

    <!-- DELETE MODAL -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Delete Modal</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="" METHOD="POST" id="deleteForm">
                    @csrf
                    @method('DELETE')
                    <div class="modal-body">
                        <p>Are you sure you want to delete Category??</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-danger">Delete Category</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection

@section('page-level-scripts')
    <script type="text/javascript">
        function displayModalForm($categoryId) {
            var url = '/categories/' + $categoryId;
            $("#deleteForm").attr('action', url);
        }
    </script>
@endsection